project:
  type: website

website:
  title: "Data Visualization 36-613 Fall 24"
  sidebar:
    background: primary
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ryurko/mads-36613-fall24
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: lectures.qmd
        text: Lectures
      - href: demos.qmd
        text: Demos

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true



