---
title: "MADS Data Visualization 36-613"
---

This is the companion website for MADS Data Visualization course 36-613. While all of the assignments will be posted on Canvas, this website provides an alternative way to access lecture materials and additional demo files (see the see side-bar).

__Lectures are on Mondays and Wednesdays from 9:30 - 10:50 AM ET, located in WEH 4709.__

Office hours schedule:

| Name                 | Office hours       | Location        |
|----------------------|--------------------|-----------------|
| Prof Yurko           | M/W 11 AM - 12 PM  | Baker Hall 132D |
| Anna Rosengart       | Tuesday 1 - 2  PM  | Zoom            |

There are no required textbooks for this course, but the following are useful free resources that I will sometimes refer to as recommended reading:

+ [R for Data Science](https://r4ds.hadley.nz/)

+ [Data Visualization: A Practical Introduction](https://socviz.co/index.html#preface)

+ [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/index.html)

+ [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)

+ [Mastering Shiny](https://mastering-shiny.org/index.html)

And the following are interesting data visualization and infographics websites:

+ [FlowingData](https://flowingdata.com/)

+ [History of Data Visualization](https://friendly.github.io/HistDataVis/)

+ [Alberto Cairo's substack](https://theartofinsight.substack.com/)

+ [Friends Don't Let Friends Make Bad Graphs](https://github.com/cxli233/FriendsDontLetFriends)



