---
title: "Lectures"
---

| Lecture   | Date    | Title                                | Materials                              |
|-----------|---------|--------------------------------------|----------------------------------------|
| 1         | Aug 26  | Introduction and Grammar of Graphics | [slides](lectures/01-intro.qmd)        |
| 2         | Aug 28  | Principles and 1D Categorical Data   | [slides](lectures/02-categorical.qmd)  |
| 3         | Sept 4  | 2D Categorical and 1D Quantitative Data  | [slides](lectures/03-2dcategorical-1dquant.qmd)  |
| 4         | Sept 9  | Visualizing Quantitative Distributions  | [slides](lectures/04-quant-distributions.qmd)  |
| 5         | Sept 11 | 2D Quantitative Data  | [slides](lectures/05-2dquant.qmd)  |
| 6         | Sept 16 | Into High-Dimensional Data  | [slides](lectures/06-into-highdim.qmd)  |
| 7         | Sept 18 | High-Dimensional Data  | [slides](lectures/07-highdim-methods.qmd)  |
| 8         | Sept 23 | t-SNE + visualizing trends and time series data  | [slides](lectures/08-tsne-trends-time-series.qmd)  |
| 9         | Sept 25 | Time series and intro to spatial data  | [slides](lectures/09-time-series-intro-spatial.qmd)  |
| 10        | Sept 30 | Areal data and creating high-quality graphics  | [slides](lectures/10-areal-data-creating-graphics.qmd)  |
| 11        | Oct 7 | Visualizing text data  | [slides](lectures/11-text-data.qmd)  |
| 12        | Oct 9 | Animations, interactive elements, and Shiny  | [slides](lectures/12-animations-interactive.qmd)  |

